apiVersion: v1
kind: Service
metadata:
  name: smart-query-router-backend-svc
  namespace: smart-query-router
  labels:
    app.kubernetes.io/name: smart-query-router-backend
    app.kubernetes.io/part-of: smart-query-router
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: smart-query-router-backend
